name: archmage_app
description: A new Flutter project.

publish_to: 'none' # Prevent accidental pub.dev publishing

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: TTCommons
      fonts:
        - asset: assets/fonts/visbycf-bold.otf
        - asset: assets/fonts/visbycf-regular.otf
        - asset: assets/fonts/visbycf-medium.otf
        - asset: assets/fonts/visbycf-demibold.otf

